branches:
  only:
  - master
  - 18-ISbo-2b
  - dev
language: python
os: linux
cache: pip
before_install: cd email/18-ISbo-2b
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -v
