version: ~> 1.0
import:
- source: .travis/18-VTbo-1a.yml
  if: (((branch = issue-*)&&(head_branch = 18-VTbo-1a) ||  (branch = 18-VTbo-1a)))
- source: .travis/18-VTbo-1b.yml
  if: (((branch = issue-*)&&(head_branch = 18-VTbo-1b) ||  (branch = 18-VTbo-1b)))
- source: .travis/dev.yml
  if: ((branch = dev) || (head_branch = dev))