dist: trusty
sudo: required
matrix:
  include:
    - language: java
      branches:
        only:
        - master
        - 18-VTbo-1b
        - dev
      jdk: oraclejdk11
      before_install: 
        - cd LR/03
      addons:
        chrome: stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script:
        - mvn install
      install: 
         - wget -N http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
           -P ~/
         - unzip ~/chromedriver_linux64.zip -d ~/
         - rm ~/chromedriver_linux64.zip
         - sudo mv -f ~/chromedriver /usr/local/share/
         - sudo chmod +x /usr/local/share/chromedriver
      cache:
        directories:
          - "$HOME/.m2"
      after_success:
         - bash <(curl -s https://codecov.io/bash) 
      before_deploy:
         # Set up git user name and tag this commit
         - git config --local user.name "YOUR GIT USER NAME"
         - git config --local user.email "YOUR GIT USER EMAIL"
         - export TRAVIS_TAG=v.0.0.0.29/04/2020
         - git tag $TRAVIS_TAG
      deploy:
        api_key:
          secure: ftcjqzn+O2eTPM0oxoPvEOHQwzjC+fMd6s6VzGAv/isAxoyu4zYjV+YglG/YQ9/Na+IbRXi/Nmtj/licGo4vyDq7tx93sYi5zS22PpORSoKRlHHaXyfqD5AD2mG32aF7XxHp2mYzDC6WIiItbzBDcjkrc8lMizQU8PW0nWucDpWo+SUHKE/IR+z9NvpqTSaZfBOVVxLAEXZm7GbwHrTyhuNvkX6Encpg1RVmS7rj5Zwxu8LeDhqBBCeOAhldGSzVMEvc9T5ayne9zzjKLjX9vSQacDmQQudHe7WpXBQdYDg8iyvwS5pDw/CJgIV98yG6+G/w38kh1TQxouuSbuPfhQ+VHe8GBfFBR9n9Bo7syhcMA8Kma5lfIXLsbpUffVKPyxjrmpk0xy5I9txvsM8Ux7nFj+0cpG1eKp+65k/qyKVfW8EG9AoAjF54gvu0tBupCGiLXkdikRjiHXz9PRFgmu8MAx6MMS7/LghgMTo9lFOlUX9OEe7gmoPvc/rV+o35vwo5Lu42yifKRiAVQ/mXfrfB1+x3v4FsNpvnsx1Oswvlqeb7Iy9rlRvAILUOaoHvM9BG3xPPDaymyOlFavRHeV/zMxpSjux9/GwEoH3LGrFEV/wiyMNv/rCONlMeCNT0C4nX6BLTH929wj7mhcUCoUzqAO1oNMOxswbPB+invd0=
        skip_cleanup: true
        provider: releases
        prerelease: true	
        name: 18-VTbo-1b
        file: 
           - /home/travis/build/Students-of-the-city-of-Kostroma/trpo_automation/LR/03/target/Selen-0.1-jar-with-dependencies.jar
           - /home/travis/build/Students-of-the-city-of-Kostroma/trpo_automation/LR/03/Repository.xml
        on:
          branch: dev
          condition: $TRAVIS_COMMIT_MESSAGE == *"release"*
    - language: cpp
      branches:
        only:
          - master
          - 18-VTbo-1a
          - dev
      os: linux
      compiler: gcc
      cache: ccache
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      before_install:
        - export PATH="/usr/lib/ccache:$PATH"
        - CC=gcc-7 && CXX=g++-7
      install:
        - sudo apt-get install -y qt5-default qttools5-dev-tools
        - sudo apt-get install mesa-common-dev
        - sudo apt-get install libgl1-mesa-dev
      after_script:
        - make clean
      before_script: cd LR/07/tests
      script:
        - sudo qmake tests.pro && make
        - sudo ./tests
          # - stage: Github Release
          #   if: branch = dev
          #   script: skip
          #   deploy:
          #     provider: releases
          #     token: "$GITHUB_OAUTH_TOKEN"
          #     on:
          #       branch: dev
          #       tags: true
